### PR TITLE
Jenkins testing on github

### PR DESCRIPTION
**Pull request by shaun-meyer**

### CODE REVIEW

**Comment by TrentMorris** [comment]
Can one of the admins verify this patch?

**Comment by wallingf** [comment]
> Can one of the admins verify this patch?

```
 I don't think Shaun made me an admin, but I'll check.
```

---- Eugene

**Comment by shaun-meyer** [comment]
Haha sorry.... Trent and I are doing some testing at Banno using this
repository, because it was the only one I owned. You can ignore this, I'll
take everyone off the mailing list.

On Thu, Jul 24, 2014 at 2:04 PM, Eugene Wallingford <
notifications@github.com> wrote:

> > Can one of the admins verify this patch?
> 
> I don't think Shaun made me an admin, but I'll check.
> 
> ---- Eugene
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shaun-meyer/second-line/pull/1#issuecomment-50063033.

## 

Shaun Meyer | Intern | Data Services | ProfitStars®

Cedar Falls, Iowa 50613

**Comment by shaun-meyer** [comment]
test

```
val x  = 1
```

**Pull request closed without merging**
